<a href="https://colab.research.google.com/github/Mathieu-Germain/LogicMojo-AI-ML-April26-Mathieu/blob/main/My_Numpy_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/BikeIndia.csv')
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
df.head(20)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,4,1,1,8.378268,11.66045,51.8261,6.000868,88,1518,1606
6,7,07-01-2018,1,0,1,0,5,1,2,8.057402,10.44195,49.8696,11.304642,148,1362,1510
7,8,08-01-2018,1,0,1,0,6,0,2,6.765000,8.11270,53.5833,17.875868,68,891,959
8,9,09-01-2018,1,0,1,0,0,0,1,5.671653,5.80875,43.4167,24.250650,54,768,822
9,10,10-01-2018,1,0,1,0,1,1,1,6.184153,7.54440,48.2917,14.958889,41,1280,1321
10,11,11-01-2018,1,0,1,0,2,1,2,6.932731,9.57320,68.6364,8.182844,43,1220,1263
11,12,12-01-2018,1,0,1,0,3,1,1,7.081807,8.02365,59.9545,20.410009,25,1137,1162
12,13,13-01-2018,1,0,1,0,4,1,1,6.765000,7.54415,47.0417,20.167000,38,1368,1406
13,14,14-01-2018,1,0,1,0,5,1,1,6.595670,9.42065,53.7826,8.478716,54,1367,1421
14,15,15-01-2018,1,0,1,0,6,0,2,9.566653,12.40560,49.8750,10.583521,222,1026,1248
15,16,16-01-2018,1,0,1,0,0,0,1,9.498347,11.71085,48.3750,12.625011,251,953,1204
16,17,17-01-2018,1,0,1,1,1,0,2,7.209153,8.83855,53.7500,12.999139,117,883,1000
17,18,18-01-2018,1,0,1,0,2,1,2,8.883347,11.61665,86.1667,9.833925,9,674,683
18,19,19-01-2018,1,0,1,0,3,1,2,11.979134,14.92110,74.1739,13.957239,78,1572,1650
19,20,20-01-2018,1,0,1,0,4,1,2,10.728347,12.75250,53.8333,13.125568,83,1844,1927

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [ ]:
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [ ]:
type(df['yr'])

pandas.core.series.Series

In [ ]:
df.loc[2:6, ['windspeed', 'registered']]

   windspeed  registered
2  16.636703        1229
3  10.739832        1454
4  12.522300        1518
5   6.000868        1518
6  11.304642        1362

In [ ]:
#To set the 1st column as index
if 'instant' in df.columns:
    df.set_index('instant', inplace=True)
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
# if I run:

df.loc[2:6, ['windspeed','registered']]

         windspeed  registered
instant
2        16.652113         670
3        16.636703        1229
4        10.739832        1454
5        12.522300        1518
6         6.000868        1518

In [ ]:
# To reset index:
df.reset_index()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
df[0:1]

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985

In [ ]:
# To reset index:
df.reset_index()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
df2 = df[df['windspeed']>10][['windspeed', 'atemp','temp']]
df2.head()

         windspeed     atemp       temp
instant
1        10.749882  18.18125  14.110847
2        16.652113  17.68695  14.902598
3        16.636703   9.47025   8.050924
4        10.739832  10.60610   8.200000
5        12.522300  11.46350   9.305237

In [ ]:
df3.headf()

(488, 3)

In [ ]:
df3 = pd.merge(df,df2, how = 'left', on = ['temp','atemp'])
df3.shape

(730, 16)

In [ ]:
# Columns added: windspeed+x and windspeed_y

df3.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed_x,casual,registered,cnt,windspeed_y
0,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,10.749882
1,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,16.652113
2,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,16.636703
3,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,10.739832
4,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,12.522300

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dteday       730 non-null    object
 1   season       730 non-null    int64
 2   yr           730 non-null    int64
 3   mnth         730 non-null    int64
 4   holiday      730 non-null    int64
 5   weekday      730 non-null    int64
 6   workingday   730 non-null    int64
 7   weathersit   730 non-null    int64
 8   temp         730 non-null    float64
 9   atemp        730 non-null    float64
 10  hum          730 non-null    float64
 11  windspeed_x  730 non-null    float64
 12  casual       730 non-null    int64
 13  registered   730 non-null    int64
 14  cnt          730 non-null    int64
 15  windspeed_y  489 non-null    float64
dtypes: float64(5), int64(10), object(1)
memory usage: 91.4+ KB

In [ ]:
# to stack

pd.concat([df,df2], axis = 0 ).head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1.0,0.0,1.0,0.0,6.0,0.0,2.0,14.110847,18.18125,80.5833,10.749882,331.0,654.0,985.0
2,02-01-2018,1.0,0.0,1.0,0.0,0.0,0.0,2.0,14.902598,17.68695,69.6087,16.652113,131.0,670.0,801.0
3,03-01-2018,1.0,0.0,1.0,0.0,1.0,1.0,1.0,8.050924,9.47025,43.7273,16.636703,120.0,1229.0,1349.0
4,04-01-2018,1.0,0.0,1.0,0.0,2.0,1.0,1.0,8.200000,10.60610,59.0435,10.739832,108.0,1454.0,1562.0
5,05-01-2018,1.0,0.0,1.0,0.0,3.0,1.0,1.0,9.305237,11.46350,43.6957,12.522300,82.0,1518.0,1600.0

In [ ]:
pd.concat([df,df2], axis = 0 ).shape

(1218, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 730 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      730 non-null    object
 1   season      730 non-null    int64
 2   yr          730 non-null    int64
 3   mnth        730 non-null    int64
 4   holiday     730 non-null    int64
 5   weekday     730 non-null    int64
 6   workingday  730 non-null    int64
 7   weathersit  730 non-null    int64
 8   temp        730 non-null    float64
 9   atemp       730 non-null    float64
 10  hum         730 non-null    float64
 11  windspeed   730 non-null    float64
 12  casual      730 non-null    int64
 13  registered  730 non-null    int64
 14  cnt         730 non-null    int64
dtypes: float64(4), int64(10), object(1)
memory usage: 107.4+ KB

In [ ]:
df4 = pd.concat([df,df2], axis= 0)

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1218 entries, 1 to 730
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      730 non-null    object
 1   season      730 non-null    float64
 2   yr          730 non-null    float64
 3   mnth        730 non-null    float64
 4   holiday     730 non-null    float64
 5   weekday     730 non-null    float64
 6   workingday  730 non-null    float64
 7   weathersit  730 non-null    float64
 8   temp        1218 non-null   float64
 9   atemp       1218 non-null   float64
 10  hum         730 non-null    float64
 11  windspeed   1218 non-null   float64
 12  casual      730 non-null    float64
 13  registered  730 non-null    float64
 14  cnt         730 non-null    float64
dtypes: float64(14), object(1)
memory usage: 152.2+ KB

In [ ]:
df['count_2'] = df['cnt'].apply(lambda x : x*2) # use this construct to manipulate all the column.
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2
instant,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200

In [ ]:
df['surrogate'] = df['dteday'].astype('str') + ': ' + df['cnt'].astype('str')
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2,surrogate
instant,,,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970,01-01-2018: 985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602,02-01-2018: 801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698,03-01-2018: 1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124,04-01-2018: 1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200,05-01-2018: 1600

In [ ]:
df.shape

(730, 17)

In [ ]:
df.describe()

,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_2
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849,9016.013699
std,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647,3872.023295
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000,44.000000
25%,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000,6339.500000
50%,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000,9097.000000
75%,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000,11932.000000
max,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000,17428.000000

In [ ]:
df.describe().columns

Index(['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt', 'count_2'],
      dtype='object')

In [ ]:
# let send the non numerical value to df5
df5 = df[['temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt']]
df5.head()

              temp     atemp      hum  windspeed  casual  registered   cnt
instant
1        14.110847  18.18125  80.5833  10.749882     331         654   985
2        14.902598  17.68695  69.6087  16.652113     131         670   801
3         8.050924   9.47025  43.7273  16.636703     120        1229  1349
4         8.200000  10.60610  59.0435  10.739832     108        1454  1562
5         9.305237  11.46350  43.6957  12.522300      82        1518  1600

In [ ]:
df.drop(['count_2','surrogate'], axis = 1, inplace = True)
df.head()

KeyError: "['count_2', 'surrogate'] not found in axis"

In [ ]:
df.head()

,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,,,,,,,,,,,,,,,
1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
#correlation apply only to numerical data
df5.corr()

,temp,atemp,hum,windspeed,casual,registered,cnt
temp,1.000000,0.991696,0.128565,-0.158186,0.542731,0.539436,0.627044
atemp,0.991696,1.000000,0.141512,-0.183876,0.543362,0.543678,0.630685
hum,0.128565,0.141512,1.000000,-0.248506,-0.075211,-0.089212,-0.098543
windspeed,-0.158186,-0.183876,-0.248506,1.000000,-0.167995,-0.217914,-0.235132
casual,0.542731,0.543362,-0.075211,-0.167995,1.000000,0.394137,0.672123
registered,0.539436,0.543678,-0.089212,-0.217914,0.394137,1.000000,0.945411
cnt,0.627044,0.630685,-0.098543,-0.235132,0.672123,0.945411,1.000000

In [ ]:
df5['temp'].unique() # to get all the unique values

array([14.110847 , 14.902598 ,  8.050924 ,  8.2      ,  9.305237 ,
        8.378268 ,  8.057402 ,  6.765    ,  5.671653 ,  6.184153 ,
        6.932731 ,  7.081807 ,  6.59567  ,  9.566653 ,  9.498347 ,
        7.209153 ,  8.883347 , 11.979134 , 10.728347 ,  7.2775   ,
        2.4243464,  3.9573897,  3.9930433,  9.162598 ,  8.9175   ,
        7.995    ,  8.342598 ,  8.877402 ,  7.414153 ,  7.879134 ,
       10.66     ,  7.665237 ,  8.663464 , 11.719153 , 11.138347 ,
        9.054153 ,  5.526103 ,  5.918268 ,  7.752731 ,  9.1225   ,
       12.977402 , 17.015    , 10.909567 , 13.048701 , 17.869153 ,
       21.388347 , 16.365847 , 11.693897 , 12.436653 ,  7.471102 ,
        9.091299 , 12.121732 , 14.938268 , 11.5825   , 14.082598 ,
       16.698193 , 10.933347 , 13.735    ,  8.131653 , 15.750847 ,
       15.437402 , 10.731299 , 11.9925   , 12.129153 , 15.952731 ,
       13.495847 , 15.758268 , 13.333897 , 13.013031 , 14.973897 ,
       22.14     , 19.3725   , 13.6325   , 17.647835 , 18.108347 ,
       14.225237 , 11.685    , 10.830847 , 10.899153 , 10.374763 ,
       10.838268 , 12.4025   , 12.3      , 11.001653 , 12.915    ,
       15.511653 , 23.506653 , 16.980847 , 16.024153 , 17.9375   ,
       13.769153 , 14.0425   , 17.493347 , 24.421732 , 20.6025   ,
       16.9125   , 19.1675   , 18.313347 , 17.664153 , 18.723347 ,
       21.0125   , 20.739153 , 24.395    , 18.825847 , 13.803347 ,
       18.86     , 23.848347 , 24.873347 , 25.898347 , 25.42     ,
       25.3175   , 20.91     , 18.518347 , 22.515847 , 25.283347 ,
       19.645847 , 21.32     , 21.661653 , 21.8325   , 22.2425   ,
       21.935    , 21.354153 , 23.0625   , 23.6775   , 23.028347 ,
       22.55     , 21.764153 , 22.003347 , 24.7025   , 24.770847 ,
       27.06     , 27.094153 , 29.041653 , 27.948347 , 26.889153 ,
       27.3675   , 30.066653 , 31.775    , 31.330847 , 29.315    ,
       26.035    , 26.581653 , 27.811653 , 29.0075   , 31.809153 ,
       33.141653 , 30.955    , 29.725    , 28.3925   , 25.693347 ,
       25.761653 , 26.615847 , 28.563347 , 28.665847 , 27.914153 ,
       29.861653 , 29.690847 , 28.495    , 27.88     , 27.9825   ,
       30.510847 , 29.6225   , 30.271653 , 29.383347 , 29.793347 ,
       30.613347 , 29.52     , 30.75     , 29.075847 , 30.6475   ,
       31.2625   , 32.560847 , 27.196653 , 28.153347 , 29.485847 ,
       31.843347 , 31.501653 , 33.415    , 34.781653 , 34.815847 ,
       34.03     , 30.476653 , 31.638347 , 31.945847 , 34.371653 ,
       32.970847 , 33.039153 , 32.116653 , 29.998347 , 29.11     ,
       29.144153 , 30.4425   , 31.365    , 31.433347 , 29.4175   ,
       28.119153 , 27.743347 , 27.299153 , 28.734153 , 29.656653 ,
       29.178347 , 28.085    , 28.5975   , 28.358347 , 26.274153 ,
       27.606653 , 28.050847 , 28.7      , 28.989419 , 26.103347 ,
       26.205847 , 26.923347 , 26.855    , 26.376653 , 27.435847 ,
       24.565847 , 25.990433 , 26.65     , 26.786653 , 26.418268 ,
       26.684153 , 19.235847 , 20.158347 , 20.8075   , 24.975847 ,
       26.000847 , 23.130847 , 16.81     , 14.623347 , 19.850847 ,
       22.071653 , 20.260847 , 20.944153 , 22.174153 , 23.404153 ,
       23.233347 , 22.276653 , 24.155847 , 22.584153 , 20.773347 ,
       20.978347 , 21.900847 , 22.211299 , 19.509153 , 17.5275   ,
       17.3225   , 17.288347 , 18.996653 , 19.338347 , 19.27     ,
       13.564153 , 10.420847 , 13.085847 , 13.94     , 16.434153 ,
       15.4775   , 16.741653 , 16.536653 , 13.393347 , 14.281653 ,
       16.195    , 16.4      , 15.58     , 13.290847 , 18.074153 ,
       21.73     , 14.008347 , 11.240847 , 18.3475   , 17.083347 ,
       15.306653 , 15.375    , 15.409153 , 20.642598 , 18.791653 ,
       13.325    , 12.8125   , 12.880847 , 12.265847 , 15.819153 ,
       18.9625   , 11.924153 , 11.275    ,  9.771653 , 13.0175   ,
       10.591653 , 11.343347 , 17.561653 , 17.356653 , 11.266103 ,
       13.191299 , 12.26433  , 10.181653 , 12.778347 , 15.17     ,
       11.194763 ,  6.15     ,  4.4075   , 13.700847 , 16.126653 ,
       13.8375   ,  9.190847 , 12.656536 , 15.6825   ,  7.38     ,
        6.833347 ,  7.79     , 15.294763 ,  7.106653 ,  6.6625   ,
        8.951653 , 12.060847 , 17.425    , 12.949153 , 11.035847 ,
       15.99     , 12.846653 , 11.586969 , 14.520847 , 10.523347 ,
       10.865    , 11.514153 ,  5.2275   , 12.983347 , 14.076653 ,
       14.213347 , 11.48     , 11.800866 , 16.229153 , 18.620847 ,
       16.7075   , 11.445847 , 15.033347 , 14.725847 , 19.919153 ,
       14.486653 , 13.359153 ,  9.976653 , 16.570847 , 21.6275   ,
       16.844153 , 11.7875   , 14.831299 , 19.133347 , 23.165    ,
       23.4725   , 22.8575   , 21.080847 , 22.345    , 22.994153 ,
       21.798347 , 22.720847 , 24.668347 , 18.279153 , 13.256653 ,
       17.390847 , 17.459153 , 17.790433 , 22.208347 , 17.835    ,
       20.5      , 20.055847 , 14.296536 , 16.2975   , 18.1425   ,
       20.295    , 27.230847 , 24.941653 , 20.431653 , 21.593347 ,
       23.37     , 16.263347 , 13.188347 , 16.946653 , 19.543347 ,
       18.7575   , 15.443347 , 19.030847 , 25.146653 , 22.96     ,
       25.7275   , 25.488347 , 22.0375   , 23.575    , 21.866653 ,
       25.1125   , 25.078347 , 24.326653 , 24.6      , 25.454153 ,
       24.531653 , 25.215    , 28.29     , 29.2125   , 26.820847 ,
       23.916653 , 24.4975   , 29.554153 , 24.2925   , 23.301653 ,
       28.221653 , 32.0825   , 31.8775   , 29.349153 , 25.864153 ,
       30.715847 , 34.200847 , 33.449153 , 32.048347 , 32.014153 ,
       32.355847 , 33.9275   , 33.961653 , 35.328347 , 33.7225   ,
       28.836653 , 30.579153 , 31.296653 , 33.551653 , 32.526653 ,
       31.57     , 24.429153 , 30.408347 , 30.784153 , 30.989153 ,
       29.588347 , 29.964153 , 29.246653 , 30.8525   , 31.399153 ,
       31.535847 , 30.169153 , 28.973347 , 26.069153 , 28.529153 ,
       28.8025   , 27.128347 , 30.886653 , 29.759153 , 30.203347 ,
       27.025847 , 25.01     , 25.966653 , 23.78     , 23.814153 ,
       25.556653 , 22.6525   , 22.413347 , 21.695847 , 25.385847 ,
       24.224153 , 26.9575   , 17.049153 , 15.716653 , 19.201653 ,
       18.689153 , 21.4225   , 23.096653 , 19.9875   , 22.310847 ,
       24.0875   , 22.379153 , 19.5775   , 18.04     , 13.045462 ,
       14.6575   , 14.999153 , 14.555    , 14.439134 , 14.828347 ,
       15.955847 , 17.254153 , 19.885    , 11.855847 , 14.145    ,
       15.614153 , 15.340847 , 15.101653 , 11.411653 , 10.079153 ,
       11.958347 , 12.163347 , 11.51567  , 12.231653 , 14.2475   ,
       18.5525   , 17.971653 , 10.489153 , 13.154153 , 15.648347 ,
       12.1975   , 11.548347 , 14.8625   , 13.53     ,  9.483464 ,
       11.943464 , 10.386653 ,  8.849153 ])

In [ ]:
len(df5['temp'].unique() ) # to get all the lenght of unique value

498

In [ ]:
df5['temp'].shape # this shows that there are duplication value in there

(730,)

In [ ]:
df['temp'].quantile(0.15)

np.float64(11.621279849999999)

In [ ]:
df['temp'].describe()

count    730.000000
mean      20.319259
std        7.506729
min        2.424346
25%       13.811885
50%       20.465826
75%       26.880615
max       35.328347
Name: temp, dtype: float64

In [ ]:
df3.isnull().sum()

dteday           0
season           0
yr               0
mnth             0
holiday          0
weekday          0
workingday       0
weathersit       0
temp             0
atemp            0
hum              0
windspeed_x      0
casual           0
registered       0
cnt              0
windspeed_y    241
dtype: int64

In [ ]:
df3.isnull().sum()/len(df3) <0.3

dteday          True
season          True
yr              True
mnth            True
holiday         True
weekday         True
workingday      True
weathersit      True
temp            True
atemp           True
hum             True
windspeed_x     True
casual          True
registered      True
cnt             True
windspeed_y    False
dtype: bool

In [71]:
df3['windspeed_y'].fillna (df.windspeed.mean())

0      10.749882
1      16.652113
2      16.636703
3      10.739832
4      12.522300
         ...
725    23.458911
726    10.416557
727    12.763620
728    23.500518
729    10.374682
Name: windspeed_y, Length: 730, dtype: float64

In [72]:
df3['windspeed_y'].fillna (df.windspeed.mean())
df3.isnull().sum()

dteday           0
season           0
yr               0
mnth             0
holiday          0
weekday          0
workingday       0
weathersit       0
temp             0
atemp            0
hum              0
windspeed_x      0
casual           0
registered       0
cnt              0
windspeed_y    241
dtype: int64

In [73]:
import numpy as np

In [76]:
df[~np.isnan(df['temp'])].shape

(730, 15)

In [78]:
df6 = df.drop_duplicates() # drop duplicate for all the columns
df6.shape

(730, 15)

In [79]:
df6 = df.drop_duplicates(['temp'])
df6.shape

(498, 15)

In [80]:
df7 = df
df7.shape

(730, 15)

In [81]:
df.drop('temp', axis = 1, inplace = True)

In [82]:
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'atemp', 'hum', 'windspeed', 'casual', 'registered',
       'cnt'],
      dtype='object')

In [2]:
import numpy as np
print(np.__version__)

2.0.2

In [ ]:
l =